#!/usr/bin/env bash
set -euo pipefail

export REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export REGISTRY="${REGISTRY:-142.150.234.165:5000}"

export FLINK_RUNTIME_IMAGE_NAME="${FLINK_RUNTIME_IMAGE_NAME:-flink-runtime}"
export FLINK_RUNTIME_IMAGE_TAG="${FLINK_RUNTIME_IMAGE_TAG:-base-1-18-from-justin}"
export FLINK_BENCHMARK_IMAGE_NAME="${FLINK_BENCHMARK_IMAGE_NAME:-flink-benchmark-runtime}"
export FLINK_BENCHMARK_IMAGE_TAG="${FLINK_BENCHMARK_IMAGE_TAG:-sql-three-tables-unique}"
export OPERATOR_IMAGE_NAME="${OPERATOR_IMAGE_NAME:-flink-kubernetes-operator}"
export OPERATOR_IMAGE_TAG="${OPERATOR_IMAGE_TAG:-justin-modified}"
export OPERATOR_A4S_IMAGE_TAG="${OPERATOR_A4S_TAG:-a4s}"

export FLINK_RUNTIME_LOCAL="${FLINK_RUNTIME_IMAGE_NAME}:${FLINK_RUNTIME_IMAGE_TAG}"
export FLINK_BENCHMARK_LOCAL="${FLINK_BENCHMARK_IMAGE_NAME}:${FLINK_BENCHMARK_IMAGE_TAG}"
export OPERATOR_LOCAL="${OPERATOR_IMAGE_NAME}:${OPERATOR_IMAGE_TAG}"
export OPERATOR_A4S_LOCAL="${OPERATOR_IMAGE_NAME}:${OPERATOR_A4S_IMAGE_TAG}"

export FLINK_RUNTIME_IMAGE="${REGISTRY}/${FLINK_RUNTIME_LOCAL}"
export FLINK_BENCHMARK_IMAGE="${REGISTRY}/${FLINK_BENCHMARK_LOCAL}"
export OPERATOR_IMAGE="${REGISTRY}/${OPERATOR_LOCAL}"
export OPERATOR_A4S_IMAGE="${REGISTRY}/${OPERATOR_A4S_LOCAL}"

export NEXMARK_FLINK_VERSION="${NEXMARK_FLINK_VERSION:-1.18-SNAPSHOT}"
export KAFKA_CLIENTS_VERSION="${KAFKA_CLIENTS_VERSION:-3.4.0}"
export KAFKA_SQL_CONNECTOR_JAR="${KAFKA_SQL_CONNECTOR_JAR:-flink-sql-connector-kafka-3.3.0.jar}"
export KAFKA_CLIENTS_JAR="${KAFKA_CLIENTS_JAR:-kafka-clients-${KAFKA_CLIENTS_VERSION}.jar}"
export ROCKSDB_OPTIONS_JAR_NAME="${ROCKSDB_OPTIONS_JAR_NAME:-rocksdb-options-1.0-SNAPSHOT.jar}"

export FLINK_RUNTIME_SOURCE_DIR="${FLINK_RUNTIME_SOURCE_DIR:-sources/flink/flink-1-18-src-from-justin}"
export DATASTREAM_BENCHMARK_SOURCE_DIR="${DATASTREAM_BENCHMARK_SOURCE_DIR:-sources/benchmarks/nexmark-datastream-benchmarks-from-justin}"
export NEXMARK_SOURCE_DIR="${NEXMARK_SOURCE_DIR:-sources/benchmarks/nexmark-sql-benchmarks}"
export ROCKSDB_OPTIONS_SOURCE_DIR="${ROCKSDB_OPTIONS_SOURCE_DIR:-sources/libs/rocksdb-options}"
export OPERATOR_SOURCE_DIR="${OPERATOR_SOURCE_DIR:-sources/operators/flink-kubernetes-operator-justin}"

export FLINK_RUNTIME_SOURCE="${REPO_ROOT}/${FLINK_RUNTIME_SOURCE_DIR}"
export DATASTREAM_BENCHMARK_SOURCE="${REPO_ROOT}/${DATASTREAM_BENCHMARK_SOURCE_DIR}"
export NEXMARK_SOURCE="${REPO_ROOT}/${NEXMARK_SOURCE_DIR}"
export ROCKSDB_OPTIONS_SOURCE="${REPO_ROOT}/${ROCKSDB_OPTIONS_SOURCE_DIR}"
export OPERATOR_SOURCE="${REPO_ROOT}/${OPERATOR_SOURCE_DIR}"
export CUSTOM_KAFKA_CONNECTOR_SOURCE="${NEXMARK_SOURCE}/flink-connector-kafka-3.3.0"
